export type MlsFieldType = "dropdown" | "multi-select" | "number" | "text";

export type MlsPmField = {
  key: string;
  sheetColumn: string;
  label: string;
  type: MlsFieldType;
  required: boolean;
  options?: string[];
  rentCastSuggestionKeys?: string[];
};

export const MLS_SPREADSHEET_ID = "1cJaHHEufiluPXUOX5JaBU7AzCQP6u6QWaQqk65Kyiik";
export const MLS_TODO_SHEET = "MLS_TODO";
export const MLS_READY_SHEET = "MLS_READY";
export const MLS_COMPLETED_SHEET = "MLS_COMPLETED";

export const mlsReadyHeaders = [
  "Done",
  "Task Key",
  "Date Created",
  "Last Seen",
  "Property ID",
  "Unit ID",
  "Address",
  "Task Type",
  "Old Value",
  "New Value",
  "Notes",
  "Ready Row Created At",
  "Ready Row Updated At",
  "Ready Source",
  "RentCast Status",
  "RentCast Updated At",
  "RentCast formattedAddress",
  "RentCast addressLine1",
  "RentCast addressLine2",
  "RentCast city",
  "RentCast state",
  "RentCast zipCode",
  "RentCast county",
  "RentCast latitude",
  "RentCast longitude",
  "RentCast propertyType",
  "RentCast bedrooms",
  "RentCast bathrooms",
  "RentCast squareFootage",
  "RentCast lotSize",
  "RentCast yearBuilt",
  "RentCast assessorID",
  "RentCast legalDescription",
  "RentCast subdivision",
  "RentCast hoa",
  "RentCast cooling",
  "RentCast coolingType",
  "RentCast floorCount",
  "RentCast garage",
  "RentCast garageSpaces",
  "RentCast garageType",
  "RentCast heating",
  "RentCast heatingType",
  "RentCast pool",
  "RentCast poolType",
  "RentCast ownerOccupied",
  "Association Y/N",
  "Garage + Carport",
  "Garage Spaces",
  "Carport Spaces",
  "Waterfront",
  "Stories",
  "Senior Community Y/N",
  "Directions Not Using GPS",
  "W/D",
  "Ceiling Fans",
  "Patio Features",
  "Association Amenities",
  "Water Source",
  "Parking",
  "Cooling",
  "Heating",
  "Deposits and Fees",
  "Showing Requirements",
  "MLS_READY",
  "PM Fields Status",
  "Bot Status",
  "Bot Module",
  "Last Run ID",
  "Last Run At",
  "Last Error",
  "Last Screenshot Path",
  "Completed At",
  "MLS Listing ID",
  "Dev Seed",
  "Source TODO Row",
  "RentCast Raw JSON",
  "PM Submitted At",
  "PM Submitted By",
  "Bot Notes",
  "Completed Row Copied At",
] as const;

export const mlsPmFields: MlsPmField[] = [
  {
    key: "associationYn",
    sheetColumn: "Association Y/N",
    label: "Association Y/N",
    type: "dropdown",
    required: true,
    options: ["Yes", "No"],
    rentCastSuggestionKeys: ["RentCast hoa"],
  },
  {
    key: "garageCarport",
    sheetColumn: "Garage + Carport",
    label: "Garage + Carport",
    type: "multi-select",
    required: true,
    options: ["Garage", "No Garage", "Carport", "No Carport", "Neither"],
    rentCastSuggestionKeys: ["RentCast garage", "RentCast garageType"],
  },
  {
    key: "garageSpaces",
    sheetColumn: "Garage Spaces",
    label: "Garage Spaces",
    type: "number",
    required: true,
    rentCastSuggestionKeys: ["RentCast garageSpaces"],
  },
  {
    key: "carportSpaces",
    sheetColumn: "Carport Spaces",
    label: "Carport Spaces",
    type: "number",
    required: true,
  },
  {
    key: "waterfront",
    sheetColumn: "Waterfront",
    label: "Waterfront",
    type: "dropdown",
    required: true,
    options: ["Yes", "No"],
  },
  {
    key: "stories",
    sheetColumn: "Stories",
    label: "Stories",
    type: "number",
    required: true,
    rentCastSuggestionKeys: ["RentCast floorCount"],
  },
  {
    key: "seniorCommunityYn",
    sheetColumn: "Senior Community Y/N",
    label: "Senior Community Y/N",
    type: "dropdown",
    required: true,
    options: ["Yes", "No"],
  },
  {
    key: "directionsNotUsingGps",
    sheetColumn: "Directions Not Using GPS",
    label: "Directions Not Using GPS",
    type: "text",
    required: true,
  },
  {
    key: "wd",
    sheetColumn: "W/D",
    label: "W/D",
    type: "dropdown",
    required: true,
    options: ["Hookups", "W/D", "None"],
  },
  {
    key: "ceilingFans",
    sheetColumn: "Ceiling Fans",
    label: "Ceiling Fans",
    type: "dropdown",
    required: true,
    options: ["Yes", "No"],
  },
  {
    key: "patioFeatures",
    sheetColumn: "Patio Features",
    label: "Patio Features",
    type: "multi-select",
    required: true,
    options: ["Porch", "Patio", "Covered", "Screen"],
  },
  {
    key: "associationAmenities",
    sheetColumn: "Association Amenities",
    label: "Association Amenities",
    type: "multi-select",
    required: true,
    options: ["Pool", "Dog Park", "Clubhouse", "Pickleball", "Fitness Center", "Playground"],
    rentCastSuggestionKeys: ["RentCast pool", "RentCast poolType"],
  },
  {
    key: "waterSource",
    sheetColumn: "Water Source",
    label: "Water Source",
    type: "dropdown",
    required: true,
    options: ["Public", "Well"],
  },
  {
    key: "parking",
    sheetColumn: "Parking",
    label: "Parking",
    type: "multi-select",
    required: true,
    options: ["Attached Carport", "Attached Garage", "On Street", "Off Street"],
  },
  {
    key: "cooling",
    sheetColumn: "Cooling",
    label: "Cooling",
    type: "dropdown",
    required: true,
    options: ["Central Air", "Wall/Window Unit(s)"],
    rentCastSuggestionKeys: ["RentCast cooling", "RentCast coolingType"],
  },
  {
    key: "heating",
    sheetColumn: "Heating",
    label: "Heating",
    type: "dropdown",
    required: true,
    options: ["Heat Pump", "Other"],
    rentCastSuggestionKeys: ["RentCast heating", "RentCast heatingType"],
  },
  {
    key: "depositsAndFees",
    sheetColumn: "Deposits and Fees",
    label: "Deposits and Fees",
    type: "text",
    required: true,
  },
  {
    key: "showingRequirements",
    sheetColumn: "Showing Requirements",
    label: "Showing Requirements",
    type: "text",
    required: true,
  },
];

export const rentCastFieldMap = {
  formattedAddress: "RentCast formattedAddress",
  addressLine1: "RentCast addressLine1",
  addressLine2: "RentCast addressLine2",
  city: "RentCast city",
  state: "RentCast state",
  zipCode: "RentCast zipCode",
  county: "RentCast county",
  latitude: "RentCast latitude",
  longitude: "RentCast longitude",
  propertyType: "RentCast propertyType",
  bedrooms: "RentCast bedrooms",
  bathrooms: "RentCast bathrooms",
  squareFootage: "RentCast squareFootage",
  lotSize: "RentCast lotSize",
  yearBuilt: "RentCast yearBuilt",
  assessorID: "RentCast assessorID",
  legalDescription: "RentCast legalDescription",
  subdivision: "RentCast subdivision",
  hoa: "RentCast hoa",
  "features.cooling": "RentCast cooling",
  "features.coolingType": "RentCast coolingType",
  "features.floorCount": "RentCast floorCount",
  "features.garage": "RentCast garage",
  "features.garageSpaces": "RentCast garageSpaces",
  "features.garageType": "RentCast garageType",
  "features.heating": "RentCast heating",
  "features.heatingType": "RentCast heatingType",
  "features.pool": "RentCast pool",
  "features.poolType": "RentCast poolType",
  ownerOccupied: "RentCast ownerOccupied",
} as const;

export const readySourceOptions = ["Manual Dev Seed", "RentCast", "n8n", "PM App"] as const;

export function splitMultiSelect(value: string | undefined) {
  if (!value) return [];
  return value
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean);
}

export function joinMultiSelect(values: string[]) {
  return values.map((value) => value.trim()).filter(Boolean).join(", ");
}
